### PR TITLE
Scoring system

### PR DESCRIPTION
**Pull request by ABB22denfor**

### CODE REVIEW

**Review by abbolisar — APPROVED** [review]
kool

**Review by abbmaldel — CHANGES_REQUESTED** [review]
Kolla igenom "File Guidlines"

**Review by tramvaj99 — CHANGES_REQUESTED** [review]
Make all relevant text visisble so that it isn't out of the players field of view.

**Review by tramvaj99 — APPROVED** [review]
Det ser bra ut!

**Pull request closed without merging**
