### PR TITLE
Menu interaction

### PR DESCRIPTION
**Pull request by ABB22OllOst**
Needs design 
I dont know why there are conflicts

### CODE REVIEW

**Review by abbolisar — CHANGES_REQUESTED** [review]
Extract your changes from Assets/Scenes/Barebones, move them into the real BareBones scene and then delete Assets/Scenes/Barebones

**Review by abbolisar — APPROVED** [review]
kool

**Comment by tramvaj99** [comment]
How can i test this?

**Comment by ABB22OllOst** [comment]
> How can i test this?

You have to add a XR UI to the world then add some kin of slider or button

**Review by tramvaj99 — APPROVED** [review]

**Comment by tramvaj99** [comment]
Var bara försiktiga när ni mergear, det skulle kunna uppstå problem pga olika namn på folders.

**Pull request merged**
